export interface Folder {
  id: string;
  name: string;
  channelIds: string[];
  icon?: string;
  autoGenerated?: boolean;
  categoryId?: string;
}

export interface Channel {
  id: string;
  name: string;
  url: string;
  avatarUrl?: string;
}

export interface StorageData {
  folders: Folder[];
  lastCategorization?: number;
  userPlan?: 'free' | 'premium';
}

class FolderStorage {
  private readonly STORAGE_KEY = 'folderTube_folders';
  private readonly SETTINGS_KEY = 'folderTube_settings';

  async getFolders(): Promise<Folder[]> {
    const result = await chrome.storage.sync.get(this.STORAGE_KEY);
    return result[this.STORAGE_KEY] || [];
  }

  async saveFolder(folder: Folder): Promise<void> {
    const folders = await this.getFolders();
    const existingIndex = folders.findIndex(f => f.id === folder.id);
    
    if (existingIndex >= 0) {
      folders[existingIndex] = folder;
    } else {
      folders.push(folder);
    }
    
    await chrome.storage.sync.set({ [this.STORAGE_KEY]: folders });
  }

  async saveFolders(folders: Folder[]): Promise<void> {
    await chrome.storage.sync.set({ [this.STORAGE_KEY]: folders });
  }

  async deleteFolder(folderId: string): Promise<void> {
    const folders = await this.getFolders();
    const filtered = folders.filter(f => f.id !== folderId);
    await chrome.storage.sync.set({ [this.STORAGE_KEY]: filtered });
  }

  async addChannelToFolder(folderId: string, channelId: string): Promise<void> {
    const folders = await this.getFolders();
    const folder = folders.find(f => f.id === folderId);
    
    if (folder && !folder.channelIds.includes(channelId)) {
      folder.channelIds.push(channelId);
      await this.saveFolder(folder);
    }
  }

  async removeChannelFromFolder(folderId: string, channelId: string): Promise<void> {
    const folders = await this.getFolders();
    const folder = folders.find(f => f.id === folderId);
    
    if (folder) {
      folder.channelIds = folder.channelIds.filter(id => id !== channelId);
      await this.saveFolder(folder);
    }
  }

  async moveChannel(channelId: string, fromFolderId: string, toFolderId: string): Promise<void> {
    await this.removeChannelFromFolder(fromFolderId, channelId);
    await this.addChannelToFolder(toFolderId, channelId);
  }

  async getUserPlan(): Promise<'free' | 'premium'> {
    const result = await chrome.storage.sync.get(this.SETTINGS_KEY);
    return result[this.SETTINGS_KEY]?.userPlan || 'free';
  }

  async setUserPlan(plan: 'free' | 'premium'): Promise<void> {
    const settings = await chrome.storage.sync.get(this.SETTINGS_KEY);
    await chrome.storage.sync.set({
      [this.SETTINGS_KEY]: { ...settings[this.SETTINGS_KEY], userPlan: plan }
    });
  }

  async getLastCategorizationTime(): Promise<number | undefined> {
    const result = await chrome.storage.sync.get(this.SETTINGS_KEY);
    return result[this.SETTINGS_KEY]?.lastCategorization;
  }

  async setLastCategorizationTime(timestamp: number): Promise<void> {
    const settings = await chrome.storage.sync.get(this.SETTINGS_KEY);
    await chrome.storage.sync.set({
      [this.SETTINGS_KEY]: { ...settings[this.SETTINGS_KEY], lastCategorization: timestamp }
    });
  }

  async clearAutoGeneratedFolders(): Promise<void> {
    const folders = await this.getFolders();
    const filtered = folders.filter(f => !f.autoGenerated);
    await this.saveFolders(filtered);
  }

  generateFolderId(): string {
    return `folder_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  async getStorageUsage(): Promise<{ used: number; total: number }> {
    const bytesInUse = await chrome.storage.sync.getBytesInUse();
    const totalBytes = chrome.storage.sync.QUOTA_BYTES;
    return { used: bytesInUse, total: totalBytes };
  }

  onFoldersChanged(callback: (folders: Folder[]) => void): void {
    chrome.storage.sync.onChanged.addListener((changes) => {
      if (changes[this.STORAGE_KEY]) {
        callback(changes[this.STORAGE_KEY].newValue || []);
      }
    });
  }
}

export const folderStorage = new FolderStorage();